brew "ruby@3.4"

cask "ghostty"
cask "rectangle"
cask "latest"

cask "visual-studio-code"

vscode "catppuccin.catppuccin-vsc"
vscode "catppuccin.catppuccin-vsc-icons"
vscode "dart-code.dart-code"
vscode "dart-code.flutter"
